# Generated by Django 4.2.7 on 2025-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('custodial', 'Custodial Wallet'), ('google', 'Google')], default='wallet', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
