# Generated by Django 4.2.7 on 2025-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('school_admin', 'School Admin'), ('super_admin', 'Super Admin'), ('donor', 'Donor')], default='student', max_length=20),
        ),
    ]
