# Generated by Django 4.2.7 on 2025-06-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectupdate_remove_project_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
