# Generated by Django 4.2.7 on 2025-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_email_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_method',
            field=models.CharField(choices=[('email', 'Email'), ('wallet', 'Wallet'), ('otp', 'OTP'), ('google', 'Google')], default='email', max_length=50),
        ),
    ]
