# Generated by Django 4.2.7 on 2025-09-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_school_unique_together_projectparticipant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("school_admin", "School Admin"),
                    ("super_admin", "Super Admin"),
                    ("donor", "Donor"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
