# Generated by Django 4.2.7 on 2025-10-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_school_unique_together_projectparticipant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "Classes"},
        ),
        migrations.AlterField(
            model_name="class",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(
                choices=[
                    ("Kindergarten", "Kindergarten (age ~5)"),
                    ("Grade 1", "Grade 1 (age ~6)"),
                    ("Grade 2", "Grade 2 (age ~7)"),
                    ("Grade 3", "Grade 3 (age ~8)"),
                    ("Grade 4", "Grade 4 (age ~9)"),
                    ("Grade 5", "Grade 5 (age ~10)"),
                    ("Grade 6", "Grade 6 (age ~11)"),
                    ("Grade 7", "Grade 7 (age ~12)"),
                    ("Grade 8", "Grade 8 (age ~13)"),
                    ("Grade 9", "Grade 9 (age ~14)"),
                    ("Grade 10", "Grade 10 (age ~15)"),
                    ("Grade 11", "Grade 11 (age ~16)"),
                    ("Grade 12", "Grade 12 (age ~17-18)"),
                    ("Junior College (First Year)", "Junior College (First Year)"),
                    ("Junior College (Second Year)", "Junior College (Second Year)"),
                    ("Pre-University (PUC 1st Year)", "Pre-University (PUC 1st Year)"),
                    ("Pre-University (PUC 2nd Year)", "Pre-University (PUC 2nd Year)"),
                    ("Foundation Year", "Foundation Year"),
                    ("Diploma", "Diploma"),
                    ("Vocational Course", "Vocational Course"),
                    (
                        "Technical Training / Trade School",
                        "Technical Training / Trade School",
                    ),
                    ("Associate Degree", "Associate Degree"),
                    (
                        "Undergraduate / Bachelor's Degree",
                        "Undergraduate / Bachelor's Degree (BA, BSc, BCom, etc.)",
                    ),
                    (
                        "Postgraduate / Master's Degree",
                        "Postgraduate / Master's Degree (MA, MSc, MBA, etc.)",
                    ),
                    ("Doctorate / PhD / DPhil", "Doctorate / PhD / DPhil"),
                ],
                max_length=100,
            ),
        ),
    ]
