# Generated by Django 4.2.7 on 2025-10-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_class_options_alter_class_description_and_more'),
        ('core', '0011_alter_user_role'),
    ]

    operations = [
    ]
