# Generated by Django 4.2.7 on 2026-02-21 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_merge_20251024_0243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="year_of_establishment",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2026),
                ]
            ),
        ),
    ]
